Add an example for the bpf-compatible toolchain (#5)
* add example; unfinished yet

* fix script json copy
exclude useless file in tar

* Initial working

* Fix a bug of bpf-compatible-rs

* Update makefile

* script: add output
fix btfhub directory path

* Update README_zh.md

* update bpf-compatible-rs

* Update README_zh.md

* update bpf-compatible-rs

* update bpf-compatible-sys

* update submodules

* add submodules

* add an Makefile for bpf-compatible-sys

* update btf_helper

* almost working

* fix decompress bug

* Add license header

* support static linking

* Add execsnoop example

* Remove tempfiles when cleaning

* use native btf if applies

* Define symbols to allow not linking the binary

* Add a root Makefile

* Add the forgotten `ensure_core_btf_tar` for `btf_helpers.h`

* Update README_zh.md

* Update README_zh.md

* Fix compiler warnings

* Remove the old example

* Rename the new examples

* Add readme

* Rename `example/examples` to `example/c`

* Add a makefile to run cleaning

---------

Co-authored-by: ocfox <i@ocfox.me>

diff --git a/script/btfgen b/script/btfgen
--- a/script/btfgen
+++ b/script/btfgen
@@ -2,7 +2,7 @@
 
 script_name=${0##*/}
 BTFHUB_CACHE_DIR="${BTFHUB_CACHE:-$HOME/.cache/eunomia/btfhub}"
-
+BTFHUB_REPO_URL="${BTFHUB_REPO:-https://github.com/aquasecurity/btfhub-archive}"
 usage() {
 	cat <<-EOF
 	Usage:
@@ -19,48 +19,59 @@ usage() {
 	Options:
 	  btfgen options:
       -j, --json JSON_FILE  compress tar.gz with package.json
+      -o, --output OUTPUT_PATH output tar file path
 	EOF
 }
 
 fetch() {
-  command -v git     >/dev/null 2>&1 || { echo "Error: git is not installed." >&2; exit 1; }
+  if ! command -v git &> /dev/null; then echo "Error: git is not installed."; exit 1; fi
   if [ -d "$BTFHUB_CACHE_DIR" ]; then
     echo "BTFHUB_CACHE_DIR does exist, skip fetch"
     return
   fi
 
-  mkdir -p $(dirname ${BTFHUB_CACHE_DIR})
-  git clone --depth 1 https://github.com/aquasecurity/btfhub-archive ${BTFHUB_CACHE_DIR}
+  mkdir -p ${BTFHUB_CACHE_DIR}
+  git clone --depth 1 ${BTFHUB_REPO_URL} ${BTFHUB_CACHE_DIR}/btfhub-archive
 }
 
 btfgen() {
   fetch
-  command -v bpftool >/dev/null 2>&1 || { echo "Error: bpftool is not installed." >&2; exit 1; }
-  short_args="j:f"
-	long_args="json:,file:"
+  if ! command -v bpftool &> /dev/null; then echo "Error: bpftool is not installed."; exit 1; fi
+  short_args="j:f:o:"
+	long_args="json:,file:,output:"
 	TEMP=$(getopt -o "$short_args" --long "$long_args" -n "$script_name" -- "$@") \
 		|| return 1
 	eval set -- "$TEMP";
 
-	local json file
+	local json file output
 	while [[ ${1:0:1} == - ]]; do
 		[[ $1 =~ ^-f|--|--file$ ]] && {
 			shift 1;
 			if [ -n "$1" ]; then file="$1"; shift 1; continue; fi
 		};
 		[[ $1 =~ ^-j|--json$ ]]    && { json="$2"; shift 2; continue; };
+		[[ $1 =~ ^-o|--output$ ]]    && { output="$2"; shift 2; continue; };
 		break;
 	done
 
+  if [ -z "$output" ]; then output="output.tar"; fi
+ 
   dir=$(pwd)
+
   find $BTFHUB_CACHE_DIR -name "*.tar.xz" | \
-  xargs -P 8 -I fileName sh -c 'tar xvfJ "fileName" -C "$(dirname "fileName")"'
+  xargs -P 8 -I fileName sh -c 'tar xfJ "fileName" -C "$(dirname "fileName")"'
   find $BTFHUB_CACHE_DIR -name "*.btf" | \
   xargs -P 8 -I fileName sh -c 'bpftool gen min_core_btf "fileName" "fileName" '$file''
 
-  if [ -z "$json" ]; then cp $json $BTFHUB_CACHE_DIR; fi
+  if [ -n "$json" ]; then cp $json $BTFHUB_CACHE_DIR; fi
 
-  cd $BTFHUB_CACHE_DIR && tar --exclude="*.xz" -czvf $dir/output.tar.gz .
+  cd $BTFHUB_CACHE_DIR && tar \
+    --exclude="./btfhub-archive/LICENSE" \
+    --exclude="./btfhub-archive/README.md" \
+    --exclude="./btfhub-archive/.gitignore" \
+    --exclude="./btfhub-archive/.git" \
+    --exclude="*.xz" \
+    -czf $dir/$output .
 }
 
 main() {
