fix script json copy exclude useless file in tar

diff --git a/script/btfgen b/script/btfgen
--- a/script/btfgen
+++ b/script/btfgen
@@ -23,7 +23,7 @@ usage() {
 }
 
 fetch() {
-  command -v git     >/dev/null 2>&1 || { echo "Error: git is not installed." >&2; exit 1; }
+  if ! command -v git &> /dev/null; then echo "Error: git is not installed."; exit 1; fi
   if [ -d "$BTFHUB_CACHE_DIR" ]; then
     echo "BTFHUB_CACHE_DIR does exist, skip fetch"
     return
@@ -35,7 +35,7 @@ fetch() {
 
 btfgen() {
   fetch
-  command -v bpftool >/dev/null 2>&1 || { echo "Error: bpftool is not installed." >&2; exit 1; }
+  if ! command -v bpftool &> /dev/null; then echo "Error: bpftool is not installed."; exit 1; fi
   short_args="j:f"
 	long_args="json:,file:"
 	TEMP=$(getopt -o "$short_args" --long "$long_args" -n "$script_name" -- "$@") \
@@ -54,13 +54,13 @@ btfgen() {
 
   dir=$(pwd)
   find $BTFHUB_CACHE_DIR -name "*.tar.xz" | \
-  xargs -P 8 -I fileName sh -c 'tar xvfJ "fileName" -C "$(dirname "fileName")"'
+  xargs -P 8 -I fileName sh -c 'tar xfJ "fileName" -C "$(dirname "fileName")"'
   find $BTFHUB_CACHE_DIR -name "*.btf" | \
   xargs -P 8 -I fileName sh -c 'bpftool gen min_core_btf "fileName" "fileName" '$file''
 
-  if [ -z "$json" ]; then cp $json $BTFHUB_CACHE_DIR; fi
+  if [ -n "$json" ]; then cp $json $BTFHUB_CACHE_DIR; fi
 
-  cd $BTFHUB_CACHE_DIR && tar --exclude="*.xz" -czvf $dir/output.tar.gz .
+  cd $BTFHUB_CACHE_DIR && tar --exclude="./LICENSE" --exclude="./README.md" --exclude="./.gitignore" --exclude="./.git" --exclude="*.xz" -czf $dir/output.tar.gz .
 }
 
 main() {
